version: "3.8"
services:
  teelebot:
    image: dompling/teelebot
    container_name: teelebot_cus
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD/config:/config
      - $PWD/plugins:/plugins
    extra_hosts:
      - "host.docker.internal:host-gateway" # 增加这一行
    tty: true
    stdin_open: true
